### ISSUE TITLE
Data pre process and joinly training

### ISSUE THREAD

**Issue by DelinQu** [knelk/enerf#2]
Hello [knelk](https://github.com/knelk), 

thank you very much for sharing your code on GitHub, it has been a great help to my work. However, I am confused about the undistortion of RGB and event data, and the training process. In your paper, IV. EXPERIMENTS, you mentioned merging RGB and event data together for training, but I haven't found the data loader or training code that loads RGB and event data together. Additionally, for data preprocessing, I think event and RGB data should be undistorted jointly to make sure they are aligned and then loaded together. As shown in the figure below:

![image](https://github.com/knelk/enerf/assets/60593268/e8f2b019-1182-4618-ba64-942469c1a0a3)

**Comment by knelk** [comment]
- the joint undistortion is done here: https://github.com/knelk/enerf/blob/main/scripts/undistort_images_eds.py#L178
- only used this for visualization, to check the calibration accuracy.

> RGB and event data together for training, but I haven't found the data loader or training code

Simply set the flag ``event_only = 0`` for joint training. I always compute the rgb-rays https://github.com/knelk/enerf/blob/main/nerf/provider.py#L1434

> Additionally, for data preprocessing, I think event and RGB data should be undistorted jointly to make sure 

They they not have to be pixel-aligned, the RGB camera will simply "shoot" different rays. IMO not aligning them is advantageous (but not thorough experiments done), as the new RGB rays will hit different points in the 3D volume. And you do not have resizing/cropping artefacts (in either the event data, the frames, or both, depending on where you place your new camera).

Also, e.g. on the TUM-VIE dataset, this would be very hard to achieve withouth signifcant loss of information since there is a baseline of a few centimeters between event & RGB camera.
